"""empty message

Revision ID: 6a4a588f27f6
Revises: 16d2c503725d
Create Date: 2019-04-06 21:30:04.085758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4a588f27f6'
down_revision = '16d2c503725d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consignment_note', sa.Column('signature', sa.String(length=128), nullable=True))
    op.add_column('consignment_note', sa.Column('signed_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'consignment_note', 'user', ['signed_by'], ['id'])
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'signature')
    op.drop_column('user', 'signed_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('signed_by', sa.INTEGER(), nullable=True))
    op.add_column('user', sa.Column('signature', sa.VARCHAR(length=128), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['signed_by'], ['id'])
    op.drop_constraint(None, 'consignment_note', type_='foreignkey')
    op.drop_column('consignment_note', 'signed_by')
    op.drop_column('consignment_note', 'signature')
    # ### end Alembic commands ###
